#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx,
# which listens on port 80 and serves a "Holberton School" page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
     sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Holberton School"
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
